// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHomeAppliance.Infrastructure.Data;

#nullable disable

namespace SmartHomeAppliance.Infrastructure.Migrations
{
    [DbContext(typeof(SmartHomeApplianceDbContext))]
    [Migration("20250103000543_AddedActivitiesTable")]
    partial class AddedActivitiesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4f8554d2-cfaa-44b5-90ce-e883c804ae90",
                            ConcurrencyStamp = "4f8554d2-cfaa-44b5-90ce-e883c804ae90",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "656a6079-ec9a-4a98-a484-2d1752156d60",
                            ConcurrencyStamp = "656a6079-ec9a-4a98-a484-2d1752156d60",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            RoleId = "656a6079-ec9a-4a98-a484-2d1752156d60"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "27d78708-8671-4b05-bd5e-17aa91392224",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "afbdad64-f7f8-486b-a73d-33a394da6c9e",
                            Email = "admin@smarthomeapp.bg",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Adminov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SMARTHOMEAPP.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEAZgv4bNbNUVRssQql5jDWl4yHrwJtvjVvI8+dQeGCib6hB9QWEE/Z+I9bvM2JjuTg==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://plus.unsplash.com/premium_photo-1689530775582-83b8abdb5020?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            SecurityStamp = "e61daa14-bbf1-4903-94b0-071b8a5ce7b3",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "12345678-9abc-def0-1234-56789abcdef0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3d4ba3a-be4d-4fa1-823b-bb88c4070716",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGjR9+Sgo1DUYuuc+BQu17is9kuXFioksO89/yil3JP7tiAgnX1YKGH1ZmykyWHDrA==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGiRJA_5DqmVm7TxMV7E0IzYzUujF4p3SHPg&s",
                            SecurityStamp = "d251abf3-bb77-40ec-aa13-3007196bf52e",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "abcdef12-3456-7890-abcd-ef1234567890",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72d392e8-27de-4446-b189-dfc56a6b2488",
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENDbspeizimma50JowLd/MXvIyP5/YbpN5yGCKM+uAyDUMoi3JuoR2VY84xwqrPuLg==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1511367461989-f85a21fda167",
                            SecurityStamp = "57c043db-b860-42dd-92eb-45380c4c051d",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "fedcba98-7654-3210-fedc-ba9876543210",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8de4485-e0b7-4ee2-aaea-3e5a9fd364bf",
                            Email = "guest@example.com",
                            EmailConfirmed = false,
                            FirstName = "Guest",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIVwfjqrAb4fNprfWzcNs9z/J/bp1DxDNowbnZf55J5/VxJHDDZMdgyHgPxboOW0Og==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
                            SecurityStamp = "e5d4323c-1743-4430-962e-8cf5c18b4d31",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "11223344-5566-7788-99aa-bbccddeeff00",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d8c012a-fc28-4f9d-8eb3-972909637b69",
                            Email = "moderator@smarthomeapp.bg",
                            EmailConfirmed = true,
                            FirstName = "Mod",
                            LastName = "Erator",
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@SMARTHOMEAPP.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEAzPCwnDCaeGCbJhXC1qnr+mQr+XYD4pL9PU2plnPEfnevmMTElRoFsOhcYbAvXxag==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
                            SecurityStamp = "4bd09930-8a6b-4862-aa66-8c10397df7d0",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.CartsProduct", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartsProducts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.OrdersProducts", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId", "UserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrderId", "UserId");

                    b.ToTable("OrdersProducts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Category = 0,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3694),
                            Description = "A high-definition doorbell camera with night vision and motion detection.",
                            ImageUrl = "https://m.media-amazon.com/images/I/611pxr2ITgL.jpg",
                            Name = "Smart Doorbell Camera",
                            Price = 129.99m,
                            Rating = 4,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Category = 1,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3702),
                            Description = "Color-changing LED light bulbs controllable via app or voice commands.",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0024/9803/5810/products/597853-Product-0-I-637940195577281576.jpg?v=1658439198",
                            Name = "Smart LED Light Bulbs (4-Pack)",
                            Price = 39.99m,
                            Rating = 5,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = "40941ea9-019c-415c-a101-9ccbc93a07d6",
                            Category = 2,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3705),
                            Description = "A programmable thermostat that learns your heating and cooling preferences.",
                            ImageUrl = "https://engocontrols.com/wp-content/uploads/2022/07/E901WIFI-2000x2000-1_strona_-min.png",
                            Name = "WiFi Thermostat",
                            Price = 249.99m,
                            Rating = 4,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Category = 3,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3708),
                            Description = "Refrigerator with touch screen, interior cameras, and WiFi connectivity.",
                            ImageUrl = "https://www.lifewire.com/thmb/Ib9NmsHdQ4q236zqBVxnsNYTIHA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/samsung-ha-ref-rf56k9540sr-family-hub-overview-5aa18f0e18ba010037c023a5.jpg",
                            Name = "Smart Refrigerator",
                            Price = 1599.99m,
                            Rating = 3,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = "800a6ca2-3027-4a0f-ae72-0156405a6a58",
                            Category = 4,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3719),
                            Description = "Voice-activated smart speaker with high-fidelity sound and assistant integration.",
                            ImageUrl = "https://cdn.aarp.net/content/dam/aarpe/en/home/home-family/personal-technology/info-2019/smart-speaker-uses/_jcr_content/root/container_main/container_body_main/container_body1/container_body_cf/container_image/articlecontentfragment/cfimage.coreimg.50.932.jpeg/content/dam/aarp/home-and-family/personal-technology/2019/10/1140-smart-speaker-functions.jpg",
                            Name = "Smart Speaker",
                            Price = 99.99m,
                            Rating = 4,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = "a2fa3f78-c2ce-44ae-8b3f-402f54563b30",
                            Category = 5,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3722),
                            Description = "Smart plug that monitors energy usage of connected devices in real-time.",
                            ImageUrl = "https://static.independent.co.uk/2023/01/10/16/best%20energy%20monitors%20Indybest%20copy.jpg",
                            Name = "Energy Monitor Plug",
                            Price = 24.99m,
                            Rating = 5,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Category = 6,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3725),
                            Description = "WiFi-enabled robot vacuum with auto-charge and scheduling capabilities.",
                            ImageUrl = "https://crowncleaners.org.uk/wp-content/uploads/2024/08/Robot_Vacuum_Cleaner-feature-image-blog.jpg",
                            Name = "Robot Vacuum Cleaner",
                            Price = 299.99m,
                            Rating = 5,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Category = 7,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3780),
                            Description = "Waterproof fitness tracker with heart rate monitor and sleep tracking.",
                            ImageUrl = "https://s13emagst.akamaized.net/products/62903/62902367/images/res_b892254d28f050b61467aa3472854e47.jpg",
                            Name = "Smart Fitness Tracker",
                            Price = 59.99m,
                            Rating = 4,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Category = 8,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3784),
                            Description = "Central hub to control and integrate all smart home devices.",
                            ImageUrl = "https://smartechdaily.com/wp-content/uploads/2024/05/19690_Generated_Image-1024x585.webp",
                            Name = "Smart Home Hub",
                            Price = 129.99m,
                            Rating = 3,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Category = 9,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 3, 0, 5, 41, 167, DateTimeKind.Utc).AddTicks(3787),
                            Description = "Weather-based sprinkler system for efficient garden watering.",
                            ImageUrl = "https://i.pcmag.com/imagery/reviews/05VIJDsjiZiHbe0MImRiYLr-1..v1569469978.jpg",
                            Name = "Smart Sprinkler System",
                            Price = 199.99m,
                            Rating = 2,
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = "2d5d4355-1bbd-4649-91b8-73ef4de6107b",
                            Comment = "I love how easy it is to set up this doorbell camera. The image quality is superb.",
                            ProductId = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 24, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1883),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "35ddf40b-42eb-44a9-82a7-e101f9b84efb",
                            Comment = "The refrigerator is sleek, but I think it's overpriced for the features.",
                            ProductId = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 19, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1893),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "b11307c3-44fb-4003-bfba-30833d783f00",
                            Comment = "A must-have fitness tracker for anyone serious about health.",
                            ProductId = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 14, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1897),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "0d1ee6ae-d7b4-4967-836c-6a769e651540",
                            Comment = "Fun to use and great for parties! The color-changing feature is amazing.",
                            ProductId = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 29, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1899),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "18d4cdd2-1fd8-4721-9d34-4dadd6dbac47",
                            Comment = "The robot vacuum works well on carpets and tiles but struggles with edges.",
                            ProductId = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 22, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1906),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "dedbb9ef-a8b4-47be-9149-864d78d9eb4a",
                            Comment = "I saved so much energy with this plug. The real-time monitoring is awesome.",
                            ProductId = "a2fa3f78-c2ce-44ae-8b3f-402f54563b30",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 16, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1909),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "53896631-e52f-4d0e-b8f5-2d108139edcc",
                            Comment = "This thermostat was a game-changer for our energy bills.",
                            ProductId = "40941ea9-019c-415c-a101-9ccbc93a07d6",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 9, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1911),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "bd33941d-bfda-4b40-9706-70edb63368db",
                            Comment = "The weather-based feature works like a charm for my garden.",
                            ProductId = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 26, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1914),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "9a2ff4f7-1191-4018-a5b7-f273649bc0e6",
                            Comment = "The hub has some lag when controlling multiple devices.",
                            ProductId = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 4, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1917),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "5786d939-5676-423e-ab83-be853f9f5f2c",
                            Comment = "The night vision is good, but the motion detection can be too sensitive.",
                            ProductId = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 20, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1920),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "7c0ab0f5-3dfe-4bae-8ea5-54f493b7742e",
                            Comment = "Perfect for busy people. It cleans thoroughly and docks automatically.",
                            ProductId = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 14, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1922),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "d1f8d21d-98ca-4c71-ac09-9c63190d5be7",
                            Comment = "Great design, but I wish the touch screen was more responsive.",
                            ProductId = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 12, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1925),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "38d2dccd-fb2d-47f7-98cf-fa138c4445b6",
                            Comment = "The lights are fantastic, and the app is super intuitive.",
                            ProductId = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 27, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1931),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "af656df3-9f44-4d7c-9502-a57d6153bf43",
                            Comment = "Accurate sleep tracking, but the battery life is shorter than expected.",
                            ProductId = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 23, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1933),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "300f90e9-aadb-4673-8f5a-24438a998e7a",
                            Comment = "Works well for basic needs, but advanced users may want more features.",
                            ProductId = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 18, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1936),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "94294921-5cc8-4e0d-aca4-23fb008c4e60",
                            Comment = "Easy to install and very efficient for garden watering.",
                            ProductId = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 25, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1938),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "39077d43-1c63-4e0a-9835-c04d7a286c1e",
                            Comment = "This doorbell camera works great! The motion detection is very accurate.",
                            ProductId = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 24, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1941),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "65d1b563-f121-44ca-98cc-5b425605f660",
                            Comment = "The lights are very bright and the app is easy to use.",
                            ProductId = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 14, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1944),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "4a610661-df05-4f94-a2ea-05adf9166fd0",
                            Comment = "A bit pricey, but I love how it learns my preferences!",
                            ProductId = "40941ea9-019c-415c-a101-9ccbc93a07d6",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 19, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1948),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "47e19a65-8f84-426c-8baf-fce1933311a5",
                            Comment = "The screen is impressive, but the cooling performance could be better.",
                            ProductId = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 29, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1951),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "e2c907a5-da31-4e70-a322-1dd55432412c",
                            Comment = "This vacuum cleaner has saved me so much time. Highly recommend!",
                            ProductId = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 26, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1956),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "7e50ee45-482f-4e88-b750-5a2817cf1be5",
                            Comment = "Great for tracking my workouts, but the strap feels a bit cheap.",
                            ProductId = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 22, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1959),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "38847545-f41d-477b-a9db-4365e6b76c9f",
                            Comment = "Good hub, but it doesn't support some devices I own.",
                            ProductId = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 16, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1961),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "f1347abf-8848-4384-af7d-3ac9e452eb62",
                            Comment = "The sprinkler system works well, but setup was confusing.",
                            ProductId = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 12, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1964),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "ab0529df-c084-43bf-9247-6e9864c097de",
                            Comment = "Simple to use and very informative. A must-have for saving energy.",
                            ProductId = "a2fa3f78-c2ce-44ae-8b3f-402f54563b30",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 4, 0, 5, 41, 459, DateTimeKind.Utc).AddTicks(1966),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Activity", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Cart", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.CartsProduct", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.OrdersProducts", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("OrdersProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("OrdersProducts")
                        .HasForeignKey("OrderId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("OrdersProducts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("OrdersProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
