// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHomeAppliance.Infrastructure.Data;

#nullable disable

namespace SmartHomeAppliance.Infrastructure.Migrations
{
    [DbContext(typeof(SmartHomeApplianceDbContext))]
    [Migration("20250108120457_AddedTechinicansTableAndTechniciansProducts")]
    partial class AddedTechinicansTableAndTechniciansProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4f8554d2-cfaa-44b5-90ce-e883c804ae90",
                            ConcurrencyStamp = "4f8554d2-cfaa-44b5-90ce-e883c804ae90",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "656a6079-ec9a-4a98-a484-2d1752156d60",
                            ConcurrencyStamp = "656a6079-ec9a-4a98-a484-2d1752156d60",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            RoleId = "656a6079-ec9a-4a98-a484-2d1752156d60"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "27d78708-8671-4b05-bd5e-17aa91392224",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22da9a74-94ef-4e84-934a-404abfb6af86",
                            Email = "admin@smarthomeapp.bg",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Adminov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SMARTHOMEAPP.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEEp2SS42vhsVd1tQs75e83rg1jhmIjzk+f1M88RWOQC3oZfY/mvSO5sZ+CGjYmnxlA==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://plus.unsplash.com/premium_photo-1689530775582-83b8abdb5020?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            SecurityStamp = "30adc6f1-a1f8-48a8-88b0-88ed520f30d2",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "12345678-9abc-def0-1234-56789abcdef0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0fd829c-bad1-4849-bd5a-7c0d55f64b93",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF52XHqacqNTmgZuNUVxygTE9fAJtuqlbgFLsis3/qL/FMMRQEtKUpKQRcUHbNVjQQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGiRJA_5DqmVm7TxMV7E0IzYzUujF4p3SHPg&s",
                            SecurityStamp = "63f846ff-d80b-4ebf-a6e9-76ebf85b926d",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "abcdef12-3456-7890-abcd-ef1234567890",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ebea3cee-f046-43c6-a391-33d06a722085",
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEUb20WX3eIaTHKzoafz+UMv89CTI8oTn8EdtW+jcyDYnlsQhoqMtBLL66LKbgZvhw==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1511367461989-f85a21fda167",
                            SecurityStamp = "f5b5804a-fcae-4941-b7e2-8e86137726e7",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "fedcba98-7654-3210-fedc-ba9876543210",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b9fb1d78-a604-40bb-b667-cd12a4089aa8",
                            Email = "guest@example.com",
                            EmailConfirmed = false,
                            FirstName = "Guest",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEhSclxpNb+vJBJvIthvBSgALhb68mR6WjWYuqmBvA3DEBeN9X3RbUerCCF6XG+Uuw==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
                            SecurityStamp = "29e324a2-11ed-47f6-b84f-73b448b2a8cc",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "11223344-5566-7788-99aa-bbccddeeff00",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5c96159-1e88-4f9f-b39e-23a430aef505",
                            Email = "moderator@smarthomeapp.bg",
                            EmailConfirmed = true,
                            FirstName = "Mod",
                            LastName = "Erator",
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@SMARTHOMEAPP.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEAg0sga5P0LyNvTn5JFxhYT7ymq9fiH7Hn+unN9/YXrvNtP81u4BFpNggzIM80GLDw==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
                            SecurityStamp = "559c9f84-d152-49b0-9fcf-ac964b52fcb9",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.CartsProduct", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartsProducts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.OrdersProducts", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId", "UserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrderId", "UserId");

                    b.ToTable("OrdersProducts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Category = 0,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3510),
                            Description = "A high-definition doorbell camera with night vision and motion detection.",
                            ImageUrl = "https://m.media-amazon.com/images/I/611pxr2ITgL.jpg",
                            Name = "Smart Doorbell Camera",
                            Price = 129.99m,
                            Rating = 4,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Category = 1,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3526),
                            Description = "Color-changing LED light bulbs controllable via app or voice commands.",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0024/9803/5810/products/597853-Product-0-I-637940195577281576.jpg?v=1658439198",
                            Name = "Smart LED Light Bulbs (4-Pack)",
                            Price = 39.99m,
                            Rating = 5,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = "40941ea9-019c-415c-a101-9ccbc93a07d6",
                            Category = 2,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3530),
                            Description = "A programmable thermostat that learns your heating and cooling preferences.",
                            ImageUrl = "https://engocontrols.com/wp-content/uploads/2022/07/E901WIFI-2000x2000-1_strona_-min.png",
                            Name = "WiFi Thermostat",
                            Price = 249.99m,
                            Rating = 4,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Category = 3,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3534),
                            Description = "Refrigerator with touch screen, interior cameras, and WiFi connectivity.",
                            ImageUrl = "https://www.lifewire.com/thmb/Ib9NmsHdQ4q236zqBVxnsNYTIHA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/samsung-ha-ref-rf56k9540sr-family-hub-overview-5aa18f0e18ba010037c023a5.jpg",
                            Name = "Smart Refrigerator",
                            Price = 1599.99m,
                            Rating = 3,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = "800a6ca2-3027-4a0f-ae72-0156405a6a58",
                            Category = 4,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3556),
                            Description = "Voice-activated smart speaker with high-fidelity sound and assistant integration.",
                            ImageUrl = "https://cdn.aarp.net/content/dam/aarpe/en/home/home-family/personal-technology/info-2019/smart-speaker-uses/_jcr_content/root/container_main/container_body_main/container_body1/container_body_cf/container_image/articlecontentfragment/cfimage.coreimg.50.932.jpeg/content/dam/aarp/home-and-family/personal-technology/2019/10/1140-smart-speaker-functions.jpg",
                            Name = "Smart Speaker",
                            Price = 99.99m,
                            Rating = 4,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = "a2fa3f78-c2ce-44ae-8b3f-402f54563b30",
                            Category = 5,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3560),
                            Description = "Smart plug that monitors energy usage of connected devices in real-time.",
                            ImageUrl = "https://static.independent.co.uk/2023/01/10/16/best%20energy%20monitors%20Indybest%20copy.jpg",
                            Name = "Energy Monitor Plug",
                            Price = 24.99m,
                            Rating = 5,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Category = 6,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3564),
                            Description = "WiFi-enabled robot vacuum with auto-charge and scheduling capabilities.",
                            ImageUrl = "https://crowncleaners.org.uk/wp-content/uploads/2024/08/Robot_Vacuum_Cleaner-feature-image-blog.jpg",
                            Name = "Robot Vacuum Cleaner",
                            Price = 299.99m,
                            Rating = 5,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Category = 7,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3568),
                            Description = "Waterproof fitness tracker with heart rate monitor and sleep tracking.",
                            ImageUrl = "https://s13emagst.akamaized.net/products/62903/62902367/images/res_b892254d28f050b61467aa3472854e47.jpg",
                            Name = "Smart Fitness Tracker",
                            Price = 59.99m,
                            Rating = 4,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Category = 8,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3719),
                            Description = "Central hub to control and integrate all smart home devices.",
                            ImageUrl = "https://smartechdaily.com/wp-content/uploads/2024/05/19690_Generated_Image-1024x585.webp",
                            Name = "Smart Home Hub",
                            Price = 129.99m,
                            Rating = 3,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Category = 9,
                            CreatorId = "27d78708-8671-4b05-bd5e-17aa91392224",
                            DateCreated = new DateTime(2025, 1, 8, 12, 4, 55, 730, DateTimeKind.Utc).AddTicks(3724),
                            Description = "Weather-based sprinkler system for efficient garden watering.",
                            ImageUrl = "https://i.pcmag.com/imagery/reviews/05VIJDsjiZiHbe0MImRiYLr-1..v1569469978.jpg",
                            Name = "Smart Sprinkler System",
                            Price = 199.99m,
                            Rating = 2,
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = "5c76e313-10ed-4e55-b8c1-e2e4007bb8c6",
                            Comment = "I love how easy it is to set up this doorbell camera. The image quality is superb.",
                            ProductId = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 29, 12, 4, 56, 73, DateTimeKind.Utc).AddTicks(9981),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "350a0a67-e525-4d1d-8f28-835ca60942fb",
                            Comment = "The refrigerator is sleek, but I think it's overpriced for the features.",
                            ProductId = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 24, 12, 4, 56, 73, DateTimeKind.Utc).AddTicks(9985),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "3a121b26-8e73-4e72-a5d7-5acab2f56711",
                            Comment = "A must-have fitness tracker for anyone serious about health.",
                            ProductId = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 19, 12, 4, 56, 73, DateTimeKind.Utc).AddTicks(9988),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "623d2da4-4751-4c58-917f-2ae342735b24",
                            Comment = "Fun to use and great for parties! The color-changing feature is amazing.",
                            ProductId = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Rating = 5,
                            ReviewDate = new DateTime(2025, 1, 3, 12, 4, 56, 73, DateTimeKind.Utc).AddTicks(9992),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "a31ce277-b597-4d6f-9bfa-f2902461fc33",
                            Comment = "The robot vacuum works well on carpets and tiles but struggles with edges.",
                            ProductId = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 27, 12, 4, 56, 73, DateTimeKind.Utc).AddTicks(9995),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "be385e62-fcb6-4567-9c64-f51b8c18d0d7",
                            Comment = "I saved so much energy with this plug. The real-time monitoring is awesome.",
                            ProductId = "a2fa3f78-c2ce-44ae-8b3f-402f54563b30",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 21, 12, 4, 56, 73, DateTimeKind.Utc).AddTicks(9997),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "2c0098c5-1a2b-4874-824b-baa42e489531",
                            Comment = "This thermostat was a game-changer for our energy bills.",
                            ProductId = "40941ea9-019c-415c-a101-9ccbc93a07d6",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 14, 12, 4, 56, 73, DateTimeKind.Utc).AddTicks(9999),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "6d457590-08ab-4a67-85fe-cda6f97cda6a",
                            Comment = "The weather-based feature works like a charm for my garden.",
                            ProductId = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 31, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(2),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "78f89e36-319a-4a26-b4ad-bb5830249dd1",
                            Comment = "The hub has some lag when controlling multiple devices.",
                            ProductId = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 9, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(4),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "b2124285-7236-498f-8794-a7d9db28d4d6",
                            Comment = "The night vision is good, but the motion detection can be too sensitive.",
                            ProductId = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 25, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(6),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "b1232d5a-1e7f-4217-8641-b6915e6f2b5f",
                            Comment = "Perfect for busy people. It cleans thoroughly and docks automatically.",
                            ProductId = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 19, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(8),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "2bd8ceca-ab7d-40ae-a3d0-2eb9c77d4a2c",
                            Comment = "Great design, but I wish the touch screen was more responsive.",
                            ProductId = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 17, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(12),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "8d1aaedb-fc22-416f-837f-b8d90c0fb682",
                            Comment = "The lights are fantastic, and the app is super intuitive.",
                            ProductId = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Rating = 5,
                            ReviewDate = new DateTime(2025, 1, 1, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(14),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "262279a9-918a-4779-a74a-f87139df9edd",
                            Comment = "Accurate sleep tracking, but the battery life is shorter than expected.",
                            ProductId = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 28, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(15),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "3a41fa03-9fa3-46d2-a976-fbb6dc8de611",
                            Comment = "Works well for basic needs, but advanced users may want more features.",
                            ProductId = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 23, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(17),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "55d68a8a-0629-409e-8d1d-ff25b7c1aaba",
                            Comment = "Easy to install and very efficient for garden watering.",
                            ProductId = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 30, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(19),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "9994f084-1551-4566-a6d3-42e2e233f7a6",
                            Comment = "This doorbell camera works great! The motion detection is very accurate.",
                            ProductId = "c5a8a95c-0fe5-4f7d-9e46-0ad9fabf78ec",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 29, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(21),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "b64a8d71-ed2d-45cf-92f4-17c5ba4f2c6f",
                            Comment = "The lights are very bright and the app is easy to use.",
                            ProductId = "d39a7ae3-78c5-40ae-8569-34a0454dc909",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 19, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(23),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "5a05282d-bb89-4e15-92df-15623bbf7ad4",
                            Comment = "A bit pricey, but I love how it learns my preferences!",
                            ProductId = "40941ea9-019c-415c-a101-9ccbc93a07d6",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 24, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(27),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "9311fc29-9d0c-4b75-abe8-507431ee9378",
                            Comment = "The screen is impressive, but the cooling performance could be better.",
                            ProductId = "54a7eca8-ed42-4444-8522-d5a00310ed62",
                            Rating = 3,
                            ReviewDate = new DateTime(2025, 1, 3, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(30),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "fed1a713-de55-4538-83f6-dcf84973ab28",
                            Comment = "This vacuum cleaner has saved me so much time. Highly recommend!",
                            ProductId = "668c6a85-f13f-43e9-b898-64d210b1cd45",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 31, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(32),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        },
                        new
                        {
                            Id = "359f993d-9318-42f3-8fe8-0d27db5928d3",
                            Comment = "Great for tracking my workouts, but the strap feels a bit cheap.",
                            ProductId = "7be0663a-6953-44a8-9d06-80f1d72ce6b3",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 27, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(34),
                            UserId = "abcdef12-3456-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            Id = "19a3b5e2-7a3c-4488-84e5-cbe6c5177833",
                            Comment = "Good hub, but it doesn't support some devices I own.",
                            ProductId = "b109e70a-6b64-489f-a216-1d407abcf02f",
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 12, 21, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(36),
                            UserId = "11223344-5566-7788-99aa-bbccddeeff00"
                        },
                        new
                        {
                            Id = "2f94dbfd-484f-4f7c-b72b-d6e576406702",
                            Comment = "The sprinkler system works well, but setup was confusing.",
                            ProductId = "398a846c-2b2c-4b01-90f2-55d342268673",
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 12, 17, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(37),
                            UserId = "fedcba98-7654-3210-fedc-ba9876543210"
                        },
                        new
                        {
                            Id = "c6085d88-2996-421e-bb7e-0f990794c30e",
                            Comment = "Simple to use and very informative. A must-have for saving energy.",
                            ProductId = "a2fa3f78-c2ce-44ae-8b3f-402f54563b30",
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 12, 9, 12, 4, 56, 74, DateTimeKind.Utc).AddTicks(39),
                            UserId = "12345678-9abc-def0-1234-56789abcdef0"
                        });
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Technician", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.TechnicianProduct", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TechnicianId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId", "TechnicianId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TechniciansProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Activity", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Cart", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.CartsProduct", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.OrdersProducts", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("OrdersProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("OrdersProducts")
                        .HasForeignKey("OrderId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Technician", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.TechnicianProduct", b =>
                {
                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHomeAppliance.Infrastructure.Data.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("OrdersProducts");
                });

            modelBuilder.Entity("SmartHomeAppliance.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("OrdersProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
